### ISSUE TITLE
Are there any option for caching to faster initial loading the map?

### ISSUE THREAD

**Issue by shaiful00000** [vietmap-company/vietmap-flutter-navigation#25]
As I need to load the map several time while i am using the application. So its very sad that I need to wait till map load from scratch each time. Are there any option for caching the map?

**Comment by thanhdt1998** [comment]
Our SDK will cached after the first load. Our SDK will download the tilemap at the first time you focus (with zoom level).
You can turn off all internet and open your app to test this feature.
