### ISSUE TITLE
Route are not building in android 12 and 13 devices.

### ISSUE THREAD

**Issue by saiful00000** [vietmap-company/vietmap-flutter-navigation#26]
We have tested in android 11, 12, 13 devices.

In android 11 the map is rendering and routes are drawing in map perfectly. but in android 12 and 13 devices the routes are not drawing.

We followed the documentation have provided in pub.dev.

**Comment by thanhdt1998** [comment]
Hi @saiful00000, please upgrade to the [latest version](https://pub.dev/packages/vietmap_flutter_navigation) (v3.0.0) in the pub.dev. 
If you have any problem, please create new issue.
Thanks for your reported.
